server.port=8080

# === CẤU HÌNH CƠ SỞ DỮ LIỆU POSTGRESQL (PRODUCTION-READY) ===
# Lưu ý: Không còn dấu ngoặc nhọn < > nào nữa
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8qib44vikkc73b0akjg-a.singapore-postgres.render.com/tour_db_prod}
spring.datasource.username=${DB_USERNAME:tour_db_prod_user}
spring.datasource.password=${DB_PASSWORD:FMcESwGqNkGsviKxZN2NDGpXaYAHaOOl}
spring.datasource.driverClassName=org.postgresql.Driver

# Tự động tạo bảng
spring.jpa.hibernate.ddl-auto=update
# Khai báo loại CSDL để Spring Boot sinh cú pháp SQL chuẩn xác
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hiển thị SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Cloudinary (Dùng biến môi trường để bảo mật)
cloudinary.cloud-name=${dtsrh7tyy}
cloudinary.api-key=${331693928942422}
cloudinary.api-secret=${S56nBWIMge7k1lZgy9YfBG1RoBM}


# Tăng giới hạn dung lượng upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB